Issue 16 ResNet18
EVA6-Group-15/DLUtils pull request #17
Opened 2021-06-28 13:04 UTC by abdksyed

Added ResNet18 Model.

2021-06-28 15:35 UTC, varsha-raveendran requested changes

2021-06-28 15:35 UTC, varsha-raveendran commented on src/dlutils/models/ResNets/resnet.py
> +
@abdksyed : we need resnet34 as well right?

2021-06-29 01:31 UTC, abdksyed commented on src/dlutils/models/ResNets/resnet.py
> +
As of now, for current assignment ResNet18 is required, but will add ResNet34 too and push the change.

2021-06-29 01:33 UTC, abdksyed commented on src/dlutils/models/ResNets/resnet.py
> +
Added Resnet34!

2021-07-02 15:51 UTC, kaustubhharapanahalli approved these changes

2021-07-02 15:58 UTC, varsha-raveendran commented
@kaustubhharapanahalli : yes, we can

2021-07-05 14:41 UTC, merged